# ==========================================
# VEDIC ASTRO ENGINE - MASTER DATABASE
# ==========================================

DASHA_YEARS = {"Ketu": 7, "Venus": 20, "Sun": 6, "Moon": 10, "Mars": 7, "Rahu": 18, "Jupiter": 16, "Saturn": 19, "Mercury": 17}
DASHA_ORDER = ["Ketu", "Venus", "Sun", "Moon", "Mars", "Rahu", "Jupiter", "Saturn", "Mercury"]
RASI_RULERS = {1: "Mars", 2: "Venus", 3: "Mercury", 4: "Moon", 5: "Sun", 6: "Mercury", 7: "Venus", 8: "Mars", 9: "Jupiter", 10: "Saturn", 11: "Saturn", 12: "Jupiter"}
ZODIAC = ["", "Mesha", "Rishabha", "Mithuna", "Kataka", "Simha", "Kanya", "Thula", "Vrischika", "Dhanu", "Makara", "Kumbha", "Meena"]
TAMIL_NAMES = {"Sun": "Suriyan", "Moon": "Chandran", "Mars": "Sevvai", "Mercury": "Budhan", "Jupiter": "Guru", "Venus": "Sukran", "Saturn": "Sani", "Rahu": "Rahu", "Ketu": "Ketu"}

BINDU_RULES = {
    "Sun": {"Sun": [1, 2, 4, 7, 8, 9, 10, 11], "Moon": [3, 6, 10, 11], "Mars": [1, 2, 4, 7, 8, 9, 10, 11], "Mercury": [3, 5, 6, 9, 10, 11, 12], "Jupiter": [5, 6, 9, 11], "Venus": [6, 7, 12], "Saturn": [1, 2, 4, 7, 8, 9, 10, 11], "Lagna": [3, 4, 6, 10, 11, 12]},
    "Moon": {"Sun": [3, 6, 7, 8, 10, 11], "Moon": [1, 3, 6, 7, 10, 11], "Mars": [2, 3, 5, 6, 9, 10, 11], "Mercury": [1, 3, 4, 5, 7, 8, 10, 11], "Jupiter": [1, 4, 7, 8, 10, 11, 12], "Venus": [3, 4, 5, 7, 9, 10, 11], "Saturn": [3, 5, 6, 11], "Lagna": [3, 6, 10, 11]},
    "Mars": {"Sun": [3, 5, 6, 10, 11], "Moon": [3, 6, 11], "Mars": [1, 2, 4, 7, 8, 10, 11], "Mercury": [3, 5, 6, 11], "Jupiter": [6, 10, 11, 12], "Venus": [6, 8, 11, 12], "Saturn": [1, 4, 7, 8, 9, 10, 11], "Lagna": [1, 3, 6, 10, 11]},
    "Mercury": {"Sun": [5, 6, 9, 11, 12], "Moon": [2, 4, 6, 8, 10, 11], "Mars": [1, 2, 4, 7, 8, 9, 10, 11], "Mercury": [1, 3, 5, 6, 9, 10, 11, 12], "Jupiter": [6, 8, 11, 12], "Venus": [1, 2, 3, 4, 5, 8, 9, 11], "Saturn": [1, 2, 4, 7, 8, 9, 10, 11], "Lagna": [1, 2, 4, 6, 8, 10, 11]},
    "Jupiter": {"Sun": [1, 2, 3, 4, 7, 8, 9, 10, 11], "Moon": [2, 5, 7, 9, 11], "Mars": [1, 2, 4, 7, 8, 10, 11], "Mercury": [1, 2, 4, 5, 6, 9, 10, 11], "Jupiter": [1, 2, 3, 4, 7, 8, 10, 11], "Venus": [2, 5, 6, 9, 10, 11], "Saturn": [3, 5, 6, 12], "Lagna": [1, 2, 4, 5, 6, 7, 9, 10, 11]},
    "Venus": {"Sun": [8, 11, 12], "Moon": [1, 2, 3, 4, 5, 8, 9, 11, 12], "Mars": [3, 4, 6, 9, 11, 12], "Mercury": [3, 5, 6, 9, 11], "Jupiter": [5, 8, 9, 10, 11], "Venus": [1, 2, 3, 4, 5, 8, 9, 10, 11], "Saturn": [3, 4, 5, 8, 9, 10, 11], "Lagna": [1, 2, 3, 4, 5, 8, 9, 11]},
    "Saturn": {"Sun": [1, 2, 4, 7, 8, 10, 11], "Moon": [3, 6, 11], "Mars": [3, 5, 6, 10, 11, 12], "Mercury": [6, 8, 9, 10, 11, 12], "Jupiter": [5, 6, 11, 12], "Venus": [6, 11, 12], "Saturn": [3, 5, 6, 11], "Lagna": [1, 3, 4, 6, 10, 11]}
}

# --- RICH TEXT: IDENTITY PROFILES ---
identity_db = {
    "Mesha": {"Purpose": "To initiate, lead, and conquer new frontiers through direct and decisive action.", "Personality": "You possess a dynamic, warrior-like energy that refuses to settle. You are a pioneer who prefers immediate execution over long deliberation.", "Strengths": "Courage, rapid initiative, physical speed, and high psychological resilience.", "Weaknesses": "Impatience with delays, sudden anger, and starting projects without finishing them."},
    "Rishabha": {"Purpose": "To build lasting structures, accumulate tangible resources, and maintain stability.", "Personality": "You are the embodiment of endurance. Like the earth itself, you are deeply grounded, practical, and incredibly patient in your pursuits.", "Strengths": "Financial stability, refined aesthetic sense, fierce loyalty, and methodical patience.", "Weaknesses": "Stubbornness in arguments, possessiveness of assets, and high resistance to change."},
    "Mithuna": {"Purpose": "To communicate complex ideas, network widely, and connect disparate groups of people.", "Personality": "Your mind is a hive of activity, constantly processing information. You are the ultimate adapter, able to shift personas to fit the environment.", "Strengths": "Sharp intelligence, high adaptability, quick wit, and natural multitasking abilities.", "Weaknesses": "Inconsistency in routines, nervous anxiety, and a tendency to overthink decisions."},
    "Kataka": {"Purpose": "To nurture, protect, and build an emotional or physical legacy for your chosen family.", "Personality": "You navigate the world through deep intuition and feeling rather than cold logic. You are fiercely protective of your inner circle.", "Strengths": "Accurate intuition, deep empathy, protective nature, and high emotional intelligence.", "Weaknesses": "Unpredictable moodiness, difficulty letting go of attachments, and taking criticism personally."},
    "Simha": {"Purpose": "To lead with absolute authority, inspire the masses, and express creative genius.", "Personality": "You carry a natural air of dignity. You are driven by a profound need to create, govern, and be recognized for your unique contributions.", "Strengths": "Natural dignity, extreme generosity, charismatic leadership, and unshakeable confidence.", "Weaknesses": "Ego-driven decisions, occasional arrogance, and a constant need for external validation."},
    "Kanya": {"Purpose": "To serve the collective, organize chaotic systems, and perfect the granular details.", "Personality": "You are the master of efficiency. Your mind automatically spots flaws and operational inefficiencies that everyone else completely misses.", "Strengths": "Flawless logic, intense detail-orientation, dedication to service, and analytical power.", "Weaknesses": "Harsh criticism of self and others, chronic worry, and paralyzing perfectionism."},
    "Thula": {"Purpose": "To harmonize conflicting forces, negotiate peace, and bring aesthetic balance to the world.", "Personality": "You are the natural diplomat. You have an innate need for balance and fairness, preferring to thrive in strategic partnerships rather than alone.", "Strengths": "Inherent charm, a deep sense of justice, elite negotiation skills, and social intelligence.", "Weaknesses": "Chronic indecision, dependency on partners, and avoidance of necessary conflict."},
    "Vrischika": {"Purpose": "To transform through crisis, heal deep trauma, and uncover hidden psychological truths.", "Personality": "You operate with intense emotional depth. You are entirely uninterested in the superficial, possessing an iron will and magnetic presence.", "Strengths": "Psychological intensity, absolute resilience, investigative power, and lifelong loyalty.", "Weaknesses": "Prone to jealousy, excessive secrecy, and a vindictive nature when deeply betrayed."},
    "Dhanu": {"Purpose": "To teach universal laws, explore global horizons, and expand the collective mindset.", "Personality": "You are an eternal student and natural philosopher. Your spirit is fueled by absolute freedom, truth-seeking, and geographical exploration.", "Strengths": "Boundless optimism, synthesized wisdom, independence, and blunt honesty.", "Weaknesses": "Restlessness in routine, over-promising on deliverables, and occasional tactlessness."},
    "Makara": {"Purpose": "To govern large structures, establish enduring systems, and achieve the highest social status.", "Personality": "You are the master strategist. You view life as a long-term mountain climb, heavily valuing discipline, pragmatism, and tangible achievements.", "Strengths": "Iron discipline, calculated ambition, immense patience, and structural organization.", "Weaknesses": "Emotional coldness, bouts of pessimism, and rigidity in traditional thinking."},
    "Kumbha": {"Purpose": "To innovate outdated systems and serve the collective progression of humanity.", "Personality": "You are a visionary who thinks in terms of global systems. You are often ahead of your time, valuing intellect and freedom over past traditions.", "Strengths": "Radical innovation, systemic logic, community focus, and pure originality.", "Weaknesses": "Emotional detachment, rebellious behavior for its own sake, and intellectual stubbornness."},
    "Meena": {"Purpose": "To heal spiritual wounds, imagine new realities, and transcend the material plane.", "Personality": "You live with one foot in reality and the other in the spiritual realm. You are highly empathetic, imaginative, and sensitive to environmental energy.", "Strengths": "Boundless compassion, artistic imagination, spiritual depth, and fluid adaptability.", "Weaknesses": "Tendency toward escapism, a lack of firm boundaries, and occasional passivity."}
}

house_labels = {1: "Self & Vitality", 2: "Wealth & Family", 3: "Courage & Skill", 4: "Home & Peace", 5: "Creativity & Kids", 6: "Health & Service", 7: "Partnership", 8: "Transformation", 9: "Luck & Wisdom", 10: "Career & Status", 11: "Gains & Network", 12: "Loss & Spirit"}

# --- RICH TEXT: SCORECARD GUIDES ---
house_leverage_guide = {
    1: "You have strong natural charisma and vitality. Step directly into the spotlight. Take charge of major projects personally rather than delegating them to subordinates.",
    2: "Your financial instincts are incredibly sharp. Focus your energy on wealth accumulation and asset investment. Your voice commands authority in all family matters.",
    3: "Your self-effort is practically unstoppable. You are built to launch startups, pitch aggressive sales targets, and win through sheer initiative and communication.",
    4: "Real estate and domestic peace are your power bases. You draw immense psychological power from a stable home environment. Invest in property.",
    5: "Your creative problem-solving is at an elite level. Trust your gut in speculative decisions. Mentoring others or investing in education brings high returns.",
    6: "You are a natural problem destroyer. You thrive in high-conflict roles involving litigation, audit, medicine, or debt restructuring. Competitors cannot stand against you.",
    7: "You are designed to thrive in pairs. Form strategic alliances, joint ventures, and deep partnerships. Your spouse or primary business partner is a major source of luck.",
    8: "You have a brilliant knack for research and uncovering hidden secrets. This is ideal for investigative work, insurance, mining, or psychological transformation.",
    9: "Fortune heavily favors your higher wisdom. Expand your reach through international travel, publishing, or higher education. Mentors are key assets.",
    10: "You naturally belong in executive or public roles. Focus your energy purely on public reputation, large-scale administration, and industry authority.",
    11: "Your professional network is your actual net worth. Focus entirely on social circles, large organizations, and diversifying your income streams for massive gains.",
    12: "You excel in foreign dealings, isolated work, or global exports. Spiritual practices and periods of deep isolation physically and mentally recharge you."
}

house_effort_guide = {
    1: "Physical vitality will naturally fluctuate. You must prioritize a strict, non-negotiable fitness regime. Do not rely on natural energy; build it consciously.",
    2: "Liquid money flows out easily. You must enforce strict budget controls and conservative financial planning. Be extremely cautious with your words during family disputes.",
    3: "Your internal courage may occasionally waver. You must force yourself to communicate and take calculated risks even when you feel deep hesitation.",
    4: "Domestic peace requires constant, proactive work. Immediately fix physical home repairs and resolve lingering emotional issues with maternal figures.",
    5: "Creative blocks are highly possible. Do not gamble or speculate on high-risk assets without deep, meticulous research and extensive planning.",
    6: "Minor health issues may linger if ignored. Adopt strict preventative medicine routines. Address debts and workplace conflicts instantly before they compound.",
    7: "Relationships require highly conscious maintenance. Do not take your partners for granted, and actively avoid minor ego battles. Compromise is your required strategy.",
    8: "Unexpected, sudden obstacles will arise. Ensure all your insurance, legal, and tax documents are perfectly compliant. Avoid all high-risk shortcuts.",
    9: "Luck is not freely given to you; you must earn it through hard work. You may experience friction with mentors or authority figures. Rely entirely on self-study.",
    10: "Career stability takes longer to achieve. You must prove yourself repeatedly to superiors. Do not expect easy promotions; mathematically document all your wins.",
    11: "Your cash flow and social support may be highly inconsistent. You must actively reach out to your networks and physically bridge the gap yourself.",
    12: "Your sleep patterns may be frequently disturbed. You must practice rigid sleep hygiene. Avoid psychological escapism or overspending on luxury comforts."
}

# --- RICH TEXT: LIFESTYLE & REMEDIES ---
lifestyle_guidance = {
    "Sun": {"Daily": "Wake up before sunrise to synchronize your internal biological clock.", "Accessory": "Wear Gold or Copper ornaments. Use a high-quality red ink pen.", "Action": "Keep the East direction of your home completely clutter-free. Respect father figures.", "Avoid": "Oversleeping after sunrise and showing disrespect to government or authority.", "Benefit": "Increases core confidence, physical immunity, and overall social status.", "Deity": "Lord Shiva / Surya", "Mantra": "Om Suryaya Namaha"},
    "Moon": {"Daily": "Drink water exclusively from a silver glass. Meditate near moving water bodies.", "Accessory": "Wear pure Silver jewelry or natural pearls. Use a white or silver pen.", "Action": "Respect mother figures and actively engage in public nourishment.", "Avoid": "Dehydration, emotional eating, and sleeping in pitch darkness.", "Benefit": "Stabilizes erratic emotions, improves mental peace, and ensures deep sleep.", "Deity": "Goddess Parvati", "Mantra": "Om Chandraya Namaha"},
    "Mars": {"Daily": "Daily, intense physical exercise is absolutely mandatory to burn excess aggressive energy.", "Accessory": "Wear Copper items. Use a red ink pen for important signatures.", "Action": "Feed birds on Tuesdays and maintain high technical discipline.", "Avoid": "Suppressing frustration until it explodes, and rash driving.", "Benefit": "Boosts physical courage, technical execution skills, and victory over rivals.", "Deity": "Lord Murugan / Kartikeya", "Mantra": "Om Angarakaya Namaha"},
    "Mercury": {"Daily": "Keep your immediate workspace impeccably organized. Maintain a daily journal.", "Accessory": "Wear Emerald or Green Tourmaline. Use a green ink pen.", "Action": "Feed cows green grass and maintain meticulous oral hygiene.", "Avoid": "Physical clutter on your desk, and any form of ambiguous or deceitful speech.", "Benefit": "Sharpens business intellect, enhances communication, and speeds up cash flow.", "Deity": "Lord Vishnu", "Mantra": "Om Budhaya Namaha"},
    "Jupiter": {"Daily": "Apply a subtle saffron or turmeric tilak on your forehead after bathing.", "Accessory": "Wear Yellow Sapphire or Gold. Use a yellow or gold pen.", "Action": "Show active respect to teachers and donate consistently to educational causes.", "Avoid": "Disrespecting traditional wisdom, and physical or intellectual lethargy.", "Benefit": "Attracts generalized luck, profound wisdom, and steady financial abundance.", "Deity": "Lord Dakshinamurthy", "Mantra": "Om Gurave Namaha"},
    "Venus": {"Daily": "Use high-quality natural perfumes daily and maintain excellent physical grooming.", "Accessory": "Wear clear Diamonds or Zircon. Use a pink or white pen.", "Action": "Keep your bedroom aesthetically pleasing and impeccably tidy.", "Avoid": "Wearing torn or dirty clothes, and staying in unkempt environments.", "Benefit": "Massively enhances personal charisma, draws luxury, and ensures relationship harmony.", "Deity": "Goddess Mahalakshmi", "Mantra": "Om Shukraya Namaha"},
    "Saturn": {"Daily": "Practice strict, non-negotiable punctuality. Do not procrastinate on hard tasks.", "Accessory": "Wear Blue Sapphire or Amethyst. Use a blue or black pen.", "Action": "Offer quiet help to laborers and water the Peepal tree on Saturdays.", "Avoid": "Underpaying staff, physical laziness, and wearing dirty or torn footwear.", "Benefit": "Ensures extreme career longevity, builds iron discipline, and slowly removes major obstacles.", "Deity": "Lord Sastha / Hanuman", "Mantra": "Om Shanicharuya Namaha"},
    "Rahu": {"Daily": "Stick to a highly rigid daily routine to prevent psychological anxiety.", "Accessory": "Carry a solid silver ball in your pocket. Wear Gomed (Hessonite).", "Action": "Clean your own bathrooms personally to ground the energy.", "Avoid": "All forms of gambling, and excessive screen time late at night.", "Benefit": "Controls sudden, unpredictable life fluctuations and clears heavy mental fog.", "Deity": "Goddess Durga", "Mantra": "Om Rahave Namaha"},
    "Ketu": {"Daily": "Practice deep, silent meditation or introspective prayer daily.", "Accessory": "Wear Cat's Eye. Dress in multi-color, brown, or grey tones.", "Action": "Feed street dogs and regularly visit temples dedicated to Lord Ganesha.", "Avoid": "Overthinking past events and falling into a psychological victim mentality.", "Benefit": "Develops highly accurate intuition and rapidly removes spiritual blockages.", "Deity": "Lord Ganesha", "Mantra": "Om Ketave Namaha"}
}